### ISSUE TITLE
提交个BUG

### ISSUE THREAD

**Issue by json988** [Hitomis/FunGameRefresh#4]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Queue.peek()' on a null object reference
                                                                    at com.wifibanlv.wifipartner.views.hitblockrefresh.BattleCityView.checkTankCrash(BattleCityView.java:291)
                                                                    at com.wifibanlv.wifipartner.views.hitblockrefresh.BattleCityView.drawSelfTank(BattleCityView.java:304)
                                                                    at com.wifibanlv.wifipartner.views.hitblockrefresh.BattleCityView.drawGame(BattleCityView.java:142)
                                                                    at com.wifibanlv.wifipartner.views.hitblockrefresh.FunGameView.onDraw(FunGameView.java:115)
                                                                    at android.view.View.draw(View.java:15171)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14096)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.draw(View.java:15174)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14096)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14091)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.View.draw(View.java:14895)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
                                                                    at android.view.View.draw(View.java:15174)
                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:592)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2695)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:14096)
                                                                    at android.view.View.getDisplayList(View.java:14119)
                                                                    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
                                                                    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
                                                                    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
                                                                    at android.view.

**Comment by Hitomis** [comment]
Thanks， 我会尽快修复

**Comment by Hitomis** [comment]
请问你是如何操作才报出这个异常的

**Comment by Hitomis** [comment]
bug已经修复好了，欢迎使用
